#!/usr/bin/env python3

import sys
import csv
import yaml

from flatten import flatten

input_name = sys.argv[1]
output_name = sys.argv[2]

with open(input_name) as fin:
    contents = fin.read()

logs = [log.split('\t') for log in contents.split('\n\n')]

fout = open(output_name, 'w')

def create_writer(log, fout):
    init = flatten(yaml.load(log[1]))
    init['timestamp'] = log[0]

    writer = csv.DictWriter(fout, fieldnames=init.keys(), restval='', extrasaction='ignore')
    writer.writeheader()

    return writer

writer = create_writer(logs[0], fout)

n = len(logs)
i = 0
for log in logs:
    out = flatten(yaml.load(log[1]))
    out['timestamp'] = log[0]
    writer.writerow(out)
        
    i += 1
    if i % 100 == 0:
        print("{:.2f}%".format(i / n * 100))

fout.close()
