#!/usr/bin/env python3

import sys
import csv
import yaml

from flatten import flatten

input_name = sys.argv[1]
output_name = sys.argv[2]

with open(input_name) as fin:
    contents = fin.read()

print("Parsing YAML, this may take a couple minutes...")
entries = contents.split('---')
n = len(entries)
i = 0
data = []
for entry in entries:
    data.append(yaml.load(entry))
    i += 1
    if i % 25 == 0:
        print("{:.2f}%".format(i / n * 100))

data.sort(key=lambda d: float(d['timestamp']))
print("done")

fout = open(output_name, 'w')

def create_writer(datum, fout):
    init = flatten(datum)

    writer = csv.DictWriter(fout, fieldnames=init.keys(), restval='', extrasaction='ignore')
    writer.writeheader()

    return writer

writer = create_writer(data[0], fout)

n = len(data)
i = 0
print("Writing CSV file...")
for datum in data:
    out = flatten(datum)
    writer.writerow(out)
        
    i += 1
    if i % 100 == 0:
        print("{:.2f}%".format(i / n * 100))

fout.close()
print("done")
